# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.a

#VAGRANTFILE_API_VERSION = "2"
#NODE_COUNT = 10
#Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
#  config.vm.provision "shell", path: "../../provisioning/default_setting.sh", args: "type=file ip=13.124.6.97 host=zinst.hcdd.kr dns= http_proxy=10.53.15.219:3128"

###############################
#

    config.ssh.insert_key = "false"
    config.vm.provider "libvirt" do |libvirt|
    config.vm.synced_folder ".", "/vagrant", disabled: true
      libvirt.id_ssh_key_file = "/.key"
      libvirt.driver = "kvm"
      libvirt.memory = 8196
      libvirt.cpus = 8
      libvirt.host = "$hypervisor_ip"
      libvirt.username = "root"
      libvirt.connect_via_ssh = "true"
    end
end
