# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.a

#VAGRANTFILE_API_VERSION = "2"
#NODE_COUNT = 10
#Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
#  config.vm.provision "shell", path: "../../provisioning/default_setting.sh", args: "type=file ip=13.124.6.97 host=zinst.hcdd.kr dns= http_proxy=10.53.15.219:3128"

###############################
######## VirtualBox Box image name
#  config.vm.box = "centos7_n_zinst"
node_os="zxc"

VAGRANTFILE_API_VERSION = "2"
NODE_COUNT = 10
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

# tset node #
  NODE_COUNT.times do |n|
    nodename = "node0#{n}"
    config.vm.box = node_os 
    config.vm.define nodename do |node|
    config.vm.provision "shell", path: "../../provisioning/default_setting.sh", args: "type=file ip=13.124.6.97 host=zinst.hcdd.kr dns="
##  config.vm.provision "shell", path: "../../provisioning/default_setting.sh", args: "type= ip=$zinst_repo_ip host=$zinst_repo_host dns=$domain_server http_proxy=10.53.15.219:3128"
    config.vm.network "private_network", :dev => "eth0", :ip => "192.168.77.1#{n}"
    config.vm.network "forwarded_port", guest: "22", host: "991#{n}"
    end
  end
#################################################################VB

#provider ORACLE VirtualBox #
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
#################################################################
end
