# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.a

#VAGRANTFILE_API_VERSION = "2"
#NODE_COUNT = 10
#Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
#  config.vm.provision "shell", path: "../../provisioning/default_setting.sh", args: "type=file ip=13.124.6.97 host=zinst.hcdd.kr dns= http_proxy=10.53.15.219:3128"

###############################
#####################################################################
AAA = "HCDD"
vs_template_OS = "CentOS_TEST"
vs_user="vagrant@hcdd.local"
vs_pass="Vagrant123!@#"
vs_name="20170824_HCDD"

################# VMware vsphere vm ################################
Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "../../provisioning/default_setting.sh", args: "type=file ip=13.124.6.97 host=zinst.hcdd.kr dns="
  config.vm.synced_folder "~/.ssh/", "/tmp/conf.d/"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__auto: true, mount_options: ["dmode=777,fmode=777"]
  node_id = AAA
  config.vm.box     = 'vsphere'
  config.vm.box_url = '../../image/dummy.box'
  config.vm.boot_timeout = 300
  config.vm.hostname = "#{node_id}"
  config.ssh.insert_key = true
  config.ssh.username = "root"
  config.ssh.password = "hcdd123!@#"
################# VMware vsphere vm ################################
#provider VMWare vsphere #
  config.vm.provider :vsphere do |vsphere|
    vsphere.host                  = '10.1.2.201'
#    vsphere.name                  = vs_name
    vsphere.compute_resource_name = '10.1.2.13'
    vsphere.resource_pool_name    = 'zzz'
    vsphere.template_name         = "Template/#{vs_template_OS}"
    vsphere.vm_base_path          = "vagrant"

    vsphere.user     = vs_user
    vsphere.password = vs_pass
    vsphere.insecure = true
  end
#################################################################
end
